- windows:
	javac .\TCP\server\Connection.java .\TCP\server\Server.java .\TCP\client\Client.java .\UDP\server\Server.java .\UDP\client\Client.java

- linux:
	javac .TCP/server/Connection.java ./TCP/server/Server.java ./TCP/client/Client.java ./UDP/server/Server.java ./UDP/client/Client.java
