- windows:
	javac .\example\threadless\Paralelo.java .\example\threadless\LinhaExecucao.java .\example\threading\Paralelo.java .\example\threading\LinhaExecucao.java .\example\runnable\Paralelo.java .\example\runnable\LinhaExecucao.java .\exercise\direcionador\Connection.java .\exercise\direcionador\Direcionador.java .\exercise\emissor\Emissor.java .\exercise\receptor\Receptor.java

- linux:
	javac ./example/threadless/Paralelo.java ./example/threadless/LinhaExecucao.java ./example/threading/Paralelo.java ./example/threading/LinhaExecucao.java ./example/runnable/Paralelo.java ./example/runnable/LinhaExecucao.java ./exercise/direcionador/Connection.java ./exercise/direcionador/Direcionador.java ./exercise/emissor/Emissor.java ./exercise/receptor/Receptor.java